---

- name: Allow users in wheel group to use sudo
  ansible.builtin.lineinfile:
    state: present
    path: /etc/sudoers.d/10-wheel
    line: '%wheel ALL=(ALL:ALL) ALL'
    create: yes
    validate: 'visudo -cf %s'
    mode: 0440

- name: Install pacman hooks
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/pacman.d/hooks/
    owner: root
    group: root
    mode: 0644
  with_fileglob: "files/arch/etc/pacman.d/hooks/*.hook"

- name: Create aur_builder user
  ansible.builtin.user:
    state: present
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow aur_builder run sudo pacman without a password
  ansible.builtin.lineinfile:
    state: present
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
    mode: 0440

- name: Install base-devel group
  community.general.pacman:
    name: base-devel
    state: present
    extra_args: "--needed"

- name: Install paru
  become_user: aur_builder
  kewlfft.aur.aur:
    name: paru-bin
    state: present

- name: Install AUR packages
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present

- name: Add user to informant group
  ansible.builtin.user:
    name: "{{ user.username }}"
    groups: informant
    append: yes
  when: ansible_user is defined

- name: Enable periodic trim for SSDs
  ansible.builtin.systemd:
    name: fstrim.timer
    state: started
    enabled: yes

- name: Enable reflector service
  ansible.builtin.systemd:
    name: reflector.timer
    state: started
    enabled: yes

- name: Enable colour in pacman
  ansible.builtin.lineinfile:
    state: present
    path: /etc/pacman.conf
    insertafter: "^#Color"
    line: "Color"

- name: Enable parallel downloads in pacman
  ansible.builtin.lineinfile:
    state: present
    path: /etc/pacman.conf
    insertafter: "^#ParallelDownloads"
    line: "ParallelDownloads = {{ pacman_parallel_downloads }}"

- name: Enable ILoveCandy in pacman
  ansible.builtin.lineinfile:
    state: present
    path: /etc/pacman.conf
    insertafter: "^ParallelDownloads"
    line: "ILoveCandy"
