---

- name: Install pacman hooks
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/pacmand.d/hooks/
    owner: root
    group: root
    mode: 0644
  with_fileglob: "files/arch/etc/pacman.d/hooks/*.hook"

- name: Create aur_builder user
  become: yes
  ansible.builtin.user:
    state: present
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow aur_builder run sudo pacman without a password
  become: yes
  ansible.builtin.lineinfile:
    state: present
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
    mode: 0440

- name: Install base-devel group
  become: yes
  community.general.pacman:
    name: base-devel
    state: present
    extra_args: "--needed"

- name: Install paru
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: paru-bin
    state: present

- name: Install AUR packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present

- name: Add user to informant group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: informant
    append: yes
  when: ansible_user is defined

- name: Enable periodic trim for SSDs
  become: yes
  ansible.builtin.systemd:
    name: fstrim.timer
    # state: started  # Should be idempotent
    enabled: yes
