---

- name: Include common package variables
  ansible.builtin.include_vars: packages.yaml

- name: Install Arch packages
  community.general.pacman:
    name: "{{ common | union(uncommon.arch) }}"
    state: present
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install Ubuntu packages
  ansible.builtin.apt:
    name: "{{ common | union(uncommon.ubuntu) }}"
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"
