---

- name: Install common packages
  ansible.builtin.import_tasks: tasks/common_packages.yaml
  tags: packages

- name: Configure user
  ansible.builtin.import_tasks: tasks/user.yaml
  tags: user

- name: Configure Arch
  ansible.builtin.import_tasks: tasks/arch_configuration.yaml
  when: ansible_facts['distribution'] == "Archlinux"
  tags: arch
