---

- name: Upgrade Arch packages
  community.general.pacman:
    upgrade: yes
  when: ansible_facts['distribution'] == "Archlinux"

- name: Upgrade Ubuntu packages
  ansible.builtin.apt:
    upgrade: yes
  when: ansible_facts['distribution'] == "Ubuntu"
