---

- name: Create user
  become: yes
  ansible.builtin.user:
    name: "{{ user.username }}"
    password: "{{ user.password }}"
    shell: "{{ user.shell }}"
    groups: "{{ user.groups }}"
    append: yes

- name: Fetch authorised keys
  become: yes
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    key: "{{ user.github_ssh_keys }}"
