---
- name: Converge
  hosts: all
  become: yes

  vars:
    user_password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"

  tasks:
    - name: Include pets
      ansible.builtin.include_role:
        name: pets_playbook
