---
- name: Converge
  hosts: all

  tasks:
    - name: Ping
      ansible.builtin.ping:

- name: Include playbook
  import_playbook: ../../main.yaml
  vars:
    user_password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
