---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: arch
    box: archlinux/archlinux
    memory: 512
    cpus: 1
  - name: ubuntu-focal
    box: generic/ubuntu2004
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  ansible-galaxy install -r requirements.yaml
  yamllint ./molecule ./tasks ./vars ./main.yaml
  ansible-lint ./molecule ./tasks ./vars ./main.yaml
