---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: arch
    image: rndmh3ro/docker-arch-ansible:latest
    pre_build_image: true
  - name: ubuntu_focal
    image: rndmh3ro/docker-ubuntu2004-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint ./molecule ./tasks ./vars ./main.yaml
  ansible-lint
