---

name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Ansible Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible-lint

      - name: Lint Ansible
        run: ansible-lint --exclude ./molecule --exclude ./.github
